package com.mcp.injector.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色主题色板（与反编译产物 ColorKt 的 packed ARGB 值一致）
val PrimaryLight = Color(0xFF146C62)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9CF2E3)
val OnPrimaryContainerLight = Color(0xFF00201C)
val SecondaryLight = Color(0xFF4A635E)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E1)
val OnSecondaryContainerLight = Color(0xFF06201B)
val TertiaryLight = Color(0xFF456179)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFCCE5FF)
val OnTertiaryContainerLight = Color(0xFF001E31)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF4FBF8)
val OnBackgroundLight = Color(0xFF161D1B)
val SurfaceLight = Color(0xFFF4FBF8)
val OnSurfaceLight = Color(0xFF161D1B)
val SurfaceVariantLight = Color(0xFFDBE5E1)
val OnSurfaceVariantLight = Color(0xFF3F4946)
val OutlineLight = Color(0xFF6F7976)

// 深色主题色板
val PrimaryDark = Color(0xFF80D5C8)
val OnPrimaryDark = Color(0xFF003731)
val PrimaryContainerDark = Color(0xFF005048)
val OnPrimaryContainerDark = Color(0xFF9CF2E3)
val SecondaryDark = Color(0xFFB1CCC5)
val OnSecondaryDark = Color(0xFF1C3530)
val SecondaryContainerDark = Color(0xFF334B47)
val OnSecondaryContainerDark = Color(0xFFCCE8E1)
val TertiaryDark = Color(0xFFADCAE5)
val OnTertiaryDark = Color(0xFF143349)
val TertiaryContainerDark = Color(0xFF2D4961)
val OnTertiaryContainerDark = Color(0xFFCCE5FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0E1513)
val OnBackgroundDark = Color(0xFFDDE4E1)
val SurfaceDark = Color(0xFF0E1513)
val OnSurfaceDark = Color(0xFFDDE4E1)
val SurfaceVariantDark = Color(0xFF3F4946)
val OnSurfaceVariantDark = Color(0xFFBFC9C5)
val OutlineDark = Color(0xFF899390)

// ---- 语义状态色（成功=绿色，警告=琥珀色），深浅模式各自适配 ----
val SuccessLight = Color(0xFF3B6B3F)
val OnSuccessLight = Color(0xFFFFFFFF)
val SuccessContainerLight = Color(0xFFBCF2B0)
val OnSuccessContainerLight = Color(0xFF042301)

val WarningLight = Color(0xFF8A5A00)
val OnWarningLight = Color(0xFFFFFFFF)
val WarningContainerLight = Color(0xFFFFDEA8)
val OnWarningContainerLight = Color(0xFF2A1A00)

val SuccessDark = Color(0xFF85D68A)
val OnSuccessDark = Color(0xFF003917)
val SuccessContainerDark = Color(0xFF1B5E2C)
val OnSuccessContainerDark = Color(0xFFB7F5B7)

val WarningDark = Color(0xFFE6B84C)
val OnWarningDark = Color(0xFF442B00)
val WarningContainerDark = Color(0xFF654900)
val OnWarningContainerDark = Color(0xFFFFDDAB)
